### ISSUE TITLE
Support for tables

### ISSUE THREAD

**Issue by delepster** [chunliu/outlook-markdown#11]
Are you planning on supporting markdown tables?

Example:

|Item|Description|
|-|-|
|item 1|description 1|

**Comment by chunliu** [comment]
Thanks for raising the issue. 

Enabled the tables syntax. No style is applied to the table. You can edit the table style with Outlook when you add it to the email body. 

You will have to disable the `Substitutions > Smart Dashes` in Outlook. Otherwise, it will convert `---` to `—` automatically, which will break the tables syntax.
